name: sfence
favicon: null
layout_spectrum: 0.68275
typography_spectrum: 0.89906
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fff282'
    - '#737373'
    - '#ffffff'
    - '#a9a9a9'
    - '#e1e1e1'
  brandStrength: 0.9536551190540195
  lightness: 0.13377571338787675
  saturation: 0.7146176837850362
  rhythmicContrast: 0.19479001127183437
purpose: []
